import React from 'react';
import { useState } from 'react';
import Container from 'react-bootstrap/Container';

import 'leaflet/dist/leaflet.css';
import Map from '../components/Map/Map';
import ReportMapper from '../components/Map/ReportMapper';
import ReportSettings from '../components/Report/ReportSettings';

export default function Reports({ routes, routeIDs }) {
  //Error handling for user input
  const [error, setError] = useState(null);

  //Visual generated by the data in the back api
  const [mapReport, setMapReport] = useState(null);

  const GenerateMapReport = async (route, day, hour) => {
    //Make sure user input is valid
    if ((route == null) || (day == null) || (hour == null)) {
      setError("Error! Make sure you click a route, day, and hour!");
      return;
    } else if (error !== null) {
      setError(null);
    }

    await fetch('https://at-pt-report-backend-m2ao84298-kieranmahons-projects.vercel.app/road-data?route=' + encodeURIComponent(route) + '&day=' + encodeURIComponent(day) + '&hour=' + encodeURIComponent(hour), {
      method: 'GET',
      headers: {
        'Cache-Control': 'no-cache',
      }
    })
    .then(response => response.json())
    .then(response => {
      //Show warning message if missing
      console.log(response)
      if (response.length === 0) {
        setError("Warning! No data found!");
      }
      
      setMapReport(<ReportMapper response={ response } />);
    })
    .catch(error => console.log(error))
  }

  const mapInjection = () => {
    return mapReport;
  }

  return (
    <>
      <Container style={{ padding: '10px' }}>
        <div className="reports-container row">
          <div className='col-md-8'>
            <Map passedFunction={ mapInjection } />
          </div>
          <div className='col-md-4'>
            <ReportSettings GenerateMapReport={ GenerateMapReport } />
            <br />

            {error != null && error}
          </div>
        </div>
      </Container>
    </>
  );
}
