import React from 'react';
import { useState } from 'react';
import Container from 'react-bootstrap/Container';

import 'leaflet/dist/leaflet.css';
import Map from '../components/Map/Map';
import ReportMapper from '../components/Map/ReportMapper';
import ReportSettings from '../components/Report/ReportSettings';
import TestJSON from '../components/Report/TestJSON';

export default function Reports({ routes, routeIDs }) {
  //Visual generated by the data in the back api
  const [mapReport, setMapReport] = useState(null);

  const GenerateMapReport = async (route, startDate, endDate, startTime, endTime, minSpeed) => {
    /*await fetch('https://api-proxy.auckland-cer.cloud.edu.au/AT/gtfs/v3/routes', {
      method: 'GET',
      headers: {
        'Cache-Control': 'no-cache',
        'Ocp-Apim-Subscription-Key': '7ddfd9ea87aa41dc9fe4efb9a5318dd5',
      }
    })
    .then(response => response.json())
    .then(response => {
      setMapReport(JSON.stringify(response));
    })
    .catch(error => console.log(error))*/

    const jsonData = TestJSON();

    setMapReport(<ReportMapper data={ jsonData } />);
    //setMapReport(JSON.stringify(jsonData));
  }

  const mapInjection = () => {
    return mapReport;
  }

  return (
    <>
      <Container style={{ padding: '10px' }}>
        <div className="reports-container row">
          <div className='col-md-8'>
            <Map passedFunction={ mapInjection } />
          </div>
          <div className='col-md-4'>
            <ReportSettings GenerateMapReport={ GenerateMapReport } />
          </div>
        </div>
      </Container>
    </>
  );
}
